### ISSUE TITLE
Icon request: AutoIt

### ISSUE THREAD

**Issue by royduin** [websiddu/technology-icons#10]
I've not found a SVG, just this bitmap image:

![AutoIt](https://camo.githubusercontent.com/091b1cb8eddd6b584b4cc8f1c5aad7c307bf9dd4/68747470733a2f2f6c68342e676f6f676c6575736572636f6e74656e742e636f6d2f2d3667665f796435323958492f543459416e6d5658645a492f4141414141414141414d4d2f796e453732615443386b412f733235362f4175746f4974253235323049636f6e253235323054656d706c6174652e706e67)

**Comment by royduin** [comment]
I've used http://vectormagic.com to convert it, the result: https://drive.google.com/file/d/0B2YCwtl0fwgGcTA2Qm5idUNLUnc/view?usp=sharing

Can you add it?

**Comment by websiddu** [comment]
Done :)

**Comment by royduin** [comment]
Thanks, but it's not readable. Can it be optimized?

**Comment by royduin** [comment]
Please re-open this one.

**Comment by websiddu** [comment]
![image](https://cloud.githubusercontent.com/assets/968912/10412931/86208fdc-6f4b-11e5-81f1-89ebacb6f0c6.png)

It looks good for me!

**Comment by royduin** [comment]
Strange, this is what I see @ http://websiddu.github.io/technology-icons/ (even after a hard refresh):

![autoit](https://cloud.githubusercontent.com/assets/1703233/10413200/8828445a-6fa0-11e5-8fc6-461766056dd7.png)

**Comment by websiddu** [comment]
May be it because you are using window machine..

**Comment by royduin** [comment]
I'm still waiting for my Macbook Pro from my boss :yum: without joking, just tried it on Windows in multiple  browsers and "hard refreshed" (`CTRL-F5`) a couple of times, no luck :sob:

**Comment by websiddu** [comment]
Checking..

**Comment by websiddu** [comment]
Should work now..

**Comment by royduin** [comment]
Jup, it's working, thank you again!
