### ISSUE TITLE
Icon request: Sublime Text

### ISSUE THREAD

**Issue by royduin** [websiddu/technology-icons#11]
So far I've not found a SVG only a bitmap image:

![Sublime Text](https://camo.githubusercontent.com/26fc099e66f5835e6ef2d797e2650b758adbbd94/687474703a2f2f633735383438322e7238322e6366322e7261636b63646e2e636f6d2f7375626c696d655f746578745f69636f6e5f323138312e706e67)

I've asked at the forum, maybe someone there can provide it: http://www.sublimetext.com/forum/viewtopic.php?f=2&t=19564

**Comment by royduin** [comment]
I've used http://vectormagic.com to convert it, the result: https://drive.google.com/file/d/0B2YCwtl0fwgGOEpac1JILVF3UTg/view?usp=sharing

Can you add it?

**Comment by websiddu** [comment]
Added it :)

**Comment by royduin** [comment]
Thanks!

**Comment by tancredi** [comment]
In case a skewed SVG version is needed - had to do this for another project - https://gist.github.com/tancredi/a468b24d0f102ab9d960071290861462

**Comment by anyotherway** [comment]
Well this is a nice commercial PNG icon with tons of bitmap effects like transparency, glow, gradients and shadows. All of those effects are removed by conversion to SVG. Vector Magic has a free online conversion tool anyone can experiment with. Sublime Text 4 when it comes out may use a logo better suited to Vector, or even a vector. Bitmap effects are the global standard in logo design, for at least four good reasons.
