### ISSUE TITLE
Donate button?

### ISSUE THREAD

**Issue by royduin** [websiddu/technology-icons#14]
I like your work and help, maybe introduce a donate button on this repo?

**Comment by websiddu** [comment]
Thanks for the suggestion :) But I am panning not to do this for now..

**Comment by royduin** [comment]
If you've please let me know, I'd like to buy you a beer.

![heineken-nu-compleet-vergroend_img9002](https://cloud.githubusercontent.com/assets/1703233/10413214/ec9f1896-6fa0-11e5-8ab8-fdcf5d96e7f6.jpg)

**Comment by websiddu** [comment]
(Y)
