### ISSUE TITLE
Icon request: Dynamicweb

### ISSUE THREAD

**Issue by royduin** [websiddu/technology-icons#15]
![dw](https://cloud.githubusercontent.com/assets/1703233/10799663/38b287c0-7dae-11e5-80f3-c550905d4816.png)

But I can't find a SVG version of the logo. Maybe @nicped from @dynamicweb can help us out with a SVG version of the logo?

**Comment by nicped** [comment]
Hi
Cannot upload them here, but you can download the logo in EPS here: developer.dynamicweb.com/files/DWlogocmyk.zip. 

I don't know how to convert them to SVG... Are these ok?

BR Nicolai

**Comment by nicped** [comment]
Found an online converter. Get them in SVG here:
developer.dynamicweb.com/files/LogosSvg.zip
BR Nicolai

**Comment by royduin** [comment]
Thanks @nicped, let's wait for @websiddu to implement it.

**Comment by websiddu** [comment]
Done.

**Comment by royduin** [comment]
Thank you!
