### ISSUE TITLE
Icon requests

### ISSUE THREAD

**Issue by royduin** [websiddu/technology-icons#2]
I'd like to have some additional icons:

- LESS
- Visual Basic
- AutoIt
- CodeIgniter
- Zend Framework
- Jira
- Confluence
- Sublime Text
- Visual Studio
- SVN
- TFS
- Gulp
- Grunt
- Browsersync
- Bower
- Composer

Can you help me out with this?

**Comment by websiddu** [comment]
[x] LESS
[] Visual Basic
[] AutoIt
[x] CodeIgniter
[x] Zend Framework
[x] Jira
[x] Confluence
[] Sublime Text
[] Visual Studio
[] SVN
[] TFS
[] Gulp
[] Grunt
[] Browsersync
[x] Bower
[] Composer

**Comment by royduin** [comment]
Thank you for these icons! Can you explain how I can add the rest by myself? And the icon references has changed, the ones in the `content` from css. I had to change some. Hereby the icons:

- LESS, better use this one, the current one isn't readable: 
![LESS](https://camo.githubusercontent.com/6cf90bd5c928f5c58116666f4102371641883ad5/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313036373930372f323136303134322f30333036353666342d393462342d313165332d393865362d3732343336393830666462652e6a7067)

- Visual Basic, the old Visual Studio icon:
![Visual Studio](http://hellboundbloggers.com/wp-content/uploads/2010/04/Microsoft-Visual-Studio-2010.jpg)

- AutoIt
![AutoIt](https://lh4.googleusercontent.com/-6gf_yd529XI/T4YAnmVXdZI/AAAAAAAAAMM/ynE72aTC8kA/s256/AutoIt%2520Icon%2520Template.png)

- Sublime Text
![Sublime Text](http://c758482.r82.cf2.rackcdn.com/sublime_text_icon_2181.png)

- Visual Studio
![Visual Studio](http://www.thepowerbase.com/wp-content/uploads/2015/04/vso.png)

- SVN
![SVN](https://shutteredbutterfly.files.wordpress.com/2012/12/subversion_ai.png)

- Gulp
![Gulp](https://avatars0.githubusercontent.com/u/6200624)

- Grunt
![Grunt](https://bintrayblog.files.wordpress.com/2013/10/grunt1.png)

- Browsersync, they have already a SVG logo on there website: http://www.browsersync.io/

- Composer
![Composer](https://cdn.tutsplus.com/net/uploads/2014/01/composer-retina-preview.png)

- Selenium
![Selenium](https://avatars0.githubusercontent.com/u/983927?v=3&s=400)

**Comment by websiddu** [comment]
Its really easy.. You just have to clone the project then run `npm i` then next `grunt serve` then add your svg icons to the icons folder. Make sure that font forge is installed on your machine. 

The .svg icon should be of same size 48x48.

**Comment by royduin** [comment]
I'm going to try it, but where did you get all the `.svg`s? I've tried some online tools to convert a normal image to a svg but the results are terrible.

**Comment by websiddu** [comment]
there are no tools that convert normal images to SVG's. You have to draw it on illustrator if the svg is not available.

**Comment by royduin** [comment]
I'm not that good with Illustrator, but I'll ask a colleague of mine. My pull request is coming ;)

**Comment by royduin** [comment]
It's not going as expected, `grunt serve` doesn't do anything, it just says `Running "serve" task` and nothing happens (it looks like a watcher but if I add my new `.svg` files nothing triggers). When I run just `grunt` it looks like it's working (after adding the missing semicolon at the end of line 489 in the `Gruntfile.js`) but it removes a lot out of the `/dist/` directory and it's not creating the `.eot` file, only the `.svg`, `.ttf` and `.woff` files. 

I've uploaded all SVG's I've found so far in a zip: http://royduineveld.nl/svgs.zip. All new excepts the GIT svg, it's just a alternative which I like more than the current one.

**Comment by websiddu** [comment]
Oh you have to install grunt-cli before `npm install -g grunt-cli` then go to that folder and run `grunt serve` then put your svg files in the icons folder, then rename one of the svg icon.. the grunt:webfont task should run generating the new font files. 

By the way.. I am not able to download the svgs, can you give me a drop box link or just attach to the comment here.

**Comment by royduin** [comment]
Normally I use Gulp but Grunt works almost the same, I've installed Grunt with `npm install -g grunt-cli`, installed the project dependencies with `npm install` in the project and ran `grunt serve`, put the svg's in the folder but nothing happens (even if I run it again after that). It's a watch task right? If I run that task it stops after saying `Running "serve" task`. I'm using Cygwin on Windows, maybe that's the problem but I don't have problems with Gulp...

Hereby a Google Drive link to a zip with the svg's: https://drive.google.com/file/d/0B2YCwtl0fwgGNlY1UmJhN0NVRVE/view?usp=sharing

**Comment by royduin** [comment]
Just tried it with CMD, the `grunt serve` task works now. After installing Ruby and SASS, modifying the `bower.json` file (renamed `prismjs` to just `prism`) and ran `bower install`. But... still no `.eot` file:

![git-status](https://cloud.githubusercontent.com/assets/1703233/9832406/24d52ae4-597a-11e5-9d4c-dd1892eabd4c.png)

**Comment by websiddu** [comment]
I pushed the new version now you have.. all the icons that you sent. Thanks a lot for the .svg :)

**Comment by royduin** [comment]
Thank you! But I've got some small issues:

- Browsersync is missing, it's inside the zip I've earlier provided
- The Grunt icon isn't that nice converted to a font. Can it be optimized? 
- The Emmet icon is just a circle, the arrow inside isn't visible
- The eye from the bird of the Bower icon is to huge
- The text Less inside the Less icon isn't visible

I've tried to optimize the Less, Emmet and Bower icons, can you update with these svgs: https://drive.google.com/file/d/0B2YCwtl0fwgGODl6NHBuRktEUzA/view?usp=sharing?

More SVG's are coming soon. I'm still searching for these icons:
- Autoit
- Sublime Text
- Composer
- Selenium

I've used the Visual Studio icon for TFS and Visual Basic.

**Comment by websiddu** [comment]
1. I will add that 
2. Will optimize it 
3. Emmet looks good for me 
4. Will optimize 
5. Let me chek if I can do something 

![image](https://cloud.githubusercontent.com/assets/968912/9833729/3e149a6c-5957-11e5-8015-119f0b3a881c.png)

Thanks for the website :)

**Comment by royduin** [comment]
1. Browsersync: Please let me know when it's added
2. Grunt: That would be nice, thanks!
3. Emmet: Fixed, thanks!
4. Bower: Fixed, thanks!
5. Less: I've fixed this one already, check the link in my previous comment
6. Composer: Meanwhile there is a SVG available, see: https://github.com/composer/composer/issues/4403

**Comment by websiddu** [comment]
Sure go ahead and do that.. :) 

Thanks a lot for the composer icons.

**Comment by websiddu** [comment]
@royduin Added composer icon.

**Comment by royduin** [comment]
Thanks! I've created new issues for the rest:

- Selenium: https://github.com/websiddu/technology-icons/issues/12
- Sublime Text: https://github.com/websiddu/technology-icons/issues/11
- AutoIt: https://github.com/websiddu/technology-icons/issues/10
- Less: https://github.com/websiddu/technology-icons/issues/9
- Grunt: https://github.com/websiddu/technology-icons/issues/8
- Browsersync: https://github.com/websiddu/technology-icons/issues/7
