### ISSUE TITLE
New icon request: GoPro

### ISSUE THREAD

**Issue by pxlar8** [websiddu/technology-icons#22]
A GoPro icon would be very useful!

**Comment by websiddu** [comment]
Do you think GoPro is a technology?

**Comment by royduin** [comment]
If you ask me, not really. It's up to you but SVG's can be found here: https://upload.wikimedia.org/wikipedia/commons/c/c3/GoPro_logo.svg and here: https://upload.wikimedia.org/wikipedia/commons/6/66/GoPro.svg

**Comment by pxlar8** [comment]
I see your point, although GoPro Studio, the video/photo editor, probably figures in much the same that something like Lightroom does.  But yes, it's admittedly more hardware technology than the software/code technology focus of this set. Great collection, by the way! Thanks for creating them.

**Comment by websiddu** [comment]
Closing this :) For now.
