### ISSUE TITLE
Icon request: Browsersync

### ISSUE THREAD

**Issue by royduin** [websiddu/technology-icons#7]
The SVG can be found here: http://www.browsersync.io/img/icons/icons.svg

**Comment by royduin** [comment]
Any updates on this one?

**Comment by websiddu** [comment]
Ahh I just moved.. to my new house in Seattle.. will work on it soon :)

**Comment by royduin** [comment]
Congratulations! No worries, I'm already glad you're doing this and have published it open source.

**Comment by websiddu** [comment]
Done :)

**Comment by royduin** [comment]
Thanks! :)
