### ISSUE TITLE
Icon request: Less

### ISSUE THREAD

**Issue by royduin** [websiddu/technology-icons#9]
The SVG can be found here: http://svgporn.com/logos/less.svg. This icon is already added but the text isn't readable so I've tried to optimize the icon by removing the gradient: https://drive.google.com/file/d/0B2YCwtl0fwgGMUd4NVpQVjBpcW8/view?usp=sharing

**Comment by websiddu** [comment]
I guess, I replaced my less icon with yours.. but I will check once agian..

**Comment by royduin** [comment]
Any updates on this one?

**Comment by websiddu** [comment]
I think.. the less icon looks good for me.. Do you still want me to optimize this?

**Comment by royduin** [comment]
The text "less" is still not readable. I'd removed the background gradient as provided in the start post.

**Comment by royduin** [comment]
Any updates?

**Comment by websiddu** [comment]
Working on it now :)

**Comment by royduin** [comment]
It's weekend, relax. I was just curious, please check the other issues too.

**Comment by websiddu** [comment]
Done

**Comment by royduin** [comment]
Now it's readable, thanks!
